global:
  scrape_interval: 15s
  evaluation_interval: 30s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: audit_log
    metrics_path: /metrics
    static_configs:
      - targets: ['audit-log:4003']
